# Generated by Django 4.0.4 on 2022-05-19 21:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conditions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('water_amount', models.PositiveIntegerField(default=100)),
                ('insolation', models.CharField(choices=[('Sunny places', 'Sunny places'), ('Shady places', 'Shady places')], max_length=100)),
                ('humidity', models.CharField(choices=[('Dry places', 'Dry places'), ('Wet places', 'Wet places')], max_length=100)),
                ('world_direction', models.CharField(choices=[('North', 'North'), ('East', 'East'), ('West', 'West'), ('South', 'South')], max_length=100)),
                ('watering_period', models.PositiveIntegerField(default=1)),
                ('watering_amount', models.PositiveIntegerField(default=1)),
                ('additional_remark', models.TextField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('send_notifications', models.BooleanField(default=True)),
                ('send_emails', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('conditions', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.conditions')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
