# Generated by Django 4.0.4 on 2022-05-19 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conditions',
            options={'verbose_name_plural': 'Conditions'},
        ),
        migrations.AlterModelOptions(
            name='plant',
            options={'ordering': ['name', 'id']},
        ),
        migrations.AlterModelOptions(
            name='usersettings',
            options={'verbose_name_plural': 'User settings'},
        ),
        migrations.RenameField(
            model_name='conditions',
            old_name='additional_remark',
            new_name='additional_remarks',
        ),
    ]
