# Generated by Django 4.0.4 on 2022-05-19 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_conditions_options_alter_plant_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conditions',
            options={'ordering': ['id'], 'verbose_name_plural': 'Conditions'},
        ),
        migrations.AlterModelOptions(
            name='usersettings',
            options={'ordering': ['id'], 'verbose_name_plural': 'User settings'},
        ),
    ]
