# Generated by Django 4.0.4 on 2022-05-19 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_conditions_options_alter_usersettings_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='image_path',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
